### ISSUE TITLE
Cannot find module "bunyan"

### ISSUE THREAD

**Issue by pepesenaris** [cchamberlain/jwt-autorefresh#1]
I think its related to bunyan being declared as a dev dependency. 
I'm using node v6.2.2 (npm v3.9.5).

**Comment by cchamberlain** [comment]
Sorry for the slow response - I missed the notification.  Curious if this is still happening for you (I use this across a few projects and haven't received this). I may not receive it because I typically have bunyan as a dependency in my main app.

I've gone ahead and promoted bunyan to a full dependency and published, if this happens again, please reopen.
